### PR TITLE
eslint

### PR DESCRIPTION
**Pull request by nezed**

### CODE REVIEW

**Comment by dfilatov** [comment]
I don't like `space-in-parens` everywhere. Looks wierd and redundant.
Can't we get rid of it?

**Comment by nezed** [comment]
But makes code more readable.
Without `space-in-parens` code looks cramped.
For me its very easy to "read" code which do not looks cramped.

Some guys from Y.Maps like it too, but i dont know why it did not become a part of [ymaps/codestyle](https://github.com/ymaps/codestyle)

**Comment by dfilatov** [comment]
I don't know any popular product which uses this rule so I prefer to avoid it.

**Comment by nezed** [comment]
okay

**Comment by dfilatov** [comment]
lgtm, let's squash commits and merge

**Pull request merged**
